name: Deploy Static Nuxt Page 

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Install bun
      run: curl -fsSL https://bun.sh/install | bash

    - name: Add bun to PATH
      run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: bun install

    - name: Generate static site
      run: bun x nuxi generate

    - name: Check better-sqlite3
      run: cat bun.lock | grep better-sqlite3

    - name: Check files
      run: |
        echo "WORKSPACE root:"
        ls -l .
        echo "dist folder:"
        ls -l ./dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
